createOrReplace

	table _Measures

		measure 'ED 4-Hour Departure Rate' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, dim_measure[measure_code] = "MYH0005", dim_reported_measure[is_total] = TRUE())
			formatString: "0.0\%"

		measure 'ED Presentations' = CALCULATE(SUM(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, dim_measure[measure_code] = "MYH0011", dim_reported_measure[is_total] = TRUE())
			formatString: "#,0"

		measure 'ED Median Waiting Time' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, dim_measure[measure_code] = "MYH0010", dim_reported_measure[is_total] = TRUE())
			formatString: "0"

		measure 'Elective Median Wait' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, dim_measure[measure_code] = "MYH0009", dim_reported_measure[is_total] = TRUE())
			formatString: "0"

		measure 'Elective % Within Recommended Time' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, dim_measure[measure_code] = "MYH0008", dim_reported_measure[is_total] = TRUE())
			formatString: "0.0\%"

		measure 'Elective % Waited Over 365 Days' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, dim_measure[measure_code] = "MYH0007", dim_reported_measure[is_total] = TRUE())
			formatString: "0.0\%"

		measure 'Hospital Count' = CALCULATE(DISTINCTCOUNT(fact_measure_value[hospital_key]), fact_measure_value[hospital_key] <> -1, fact_measure_value[suppression_count] = 0)
			formatString: "#,0"

		measure 'National Benchmark Value' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0, fact_measure_value[reporting_unit_type_code] = "NAT", dim_reported_measure[is_total] = TRUE())
			formatString: "0.0"

		measure 'Selected Value' = CALCULATE(AVERAGE(fact_measure_value[value]), fact_measure_value[suppression_count] = 0)
			formatString: "0.0"

		measure 'Suppressed Data Points' = CALCULATE(COUNTROWS(fact_measure_value), fact_measure_value[suppression_count] > 0)
			formatString: "#,0"

		partition _Measures = calculated
			mode: import
			source = {BLANK()}
